version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nest_study
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'nest_study'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
